### ISSUE TITLE
Exceptions Needed

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/output-block-interface#3]
Now that blocks no longer extend output renderers, their exceptions cannot be used in blocks.

Add block-specific exceptions.

**Comment by mecha** [comment]
How can we go about this? `__toString()` cannot throw exceptions and `BlockInterface` merely extends `StringableInterface`.

**Comment by XedinUnknown** [comment]
This package is now deprecated in favour of `dhii/output-renderer-interface`
