### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by XedinUnknown** [Dhii/output-block-interface#4]
Now that `dhii/output-renderer-interface` has restored hierarchy (see Dhii/output-renderer-interface#3), block interfaces should be shifted there, and this package deprecated. This also makes #3 obsolete.

**Comment by mecha** [comment]
Consider marking the package as deprecated on Packagist, similar to how [`guzzle/guzzle`](https://packagist.org/packages/guzzle/guzzle) does it. At the time of writing, Composer does not seem to have a way to do this in `composer.json`.

**Comment by XedinUnknown** [comment]
Now deprecated on Packagist in favour of dhii/output-renderer-interface.
